### ISSUE TITLE
Gradle examples do not serve docs as static content

### ISSUE THREAD

**Issue by germans-kuzmins** [spring-projects/spring-restdocs-samples#5]
How to reproduce:

- Build restful-notes-spring-hateoas with ./gradlew build
- Run server with ./gradlew bootRun
- open http://localhost:8080/docs/api-guide.html

Expected that the rest docs would be there, but got 404. On maven projects restful-notes-spring-data-rest working.

**Comment by germans-kuzmins** [comment]
I am using following snipper:

```
tasks.register<Copy>("copyGeneratedDocsToStatic") {
	dependsOn(tasks.asciidoctor)
	mustRunAfter(tasks.resolveMainClassName)
	mustRunAfter(tasks.jar)
	// Specify the source directory
	from("${layout.buildDirectory.get()}/docs/asciidoc")
	// Specify the destination directory
	into("${layout.buildDirectory.get()}/resources/main/static/docs")
}
```

**Comment by wilkinsona** [comment]
Thanks, @germans-kuzmins. The problem was caused by not updating the source location for the Asciidoctor-generated HTML which changed when upgrading to a new version of the Asciidoctor Gradle plugin.
